---
title: "Example 1"
output:
  html_document:
    df_print: paged
---

# Load functions
```{r echo=FALSE, warning=FALSE}
source("../R/evaluate_samples.R")
source("../R/generate_samples.R")
library(ggplot2)
library(dplyr)
```

# Example 1: parallel design
In the examples there are 2 groups: treatment y control
```{r}
n_total <- 10000
n <- n_total/2
# Groups
group_1 <- c(rep(TRUE, n), rep(FALSE, n))
group_2 <- !group_1
```


## 1.A no treatment effect
First, generate the data with no treatment effect.
```{r}
set.seed(123)
# Generate data
Y_1a <- generate.samples.parallel(
  n_total=n_total, b0=120, sigma_u=20,
  treatment_effect=0
  )
# Basic summary
mean_1a <- mean(Y_1a)
sd_1a <- sd(Y_1a)
sd_1a_group1 <- sd(Y_1a[group_1])
sd_1a_group2 <- sd(Y_1a[group_2])
cat(mean_1a)
cat(sd_1a, sd_1a_group1, sd_1a_group2)
```

Plot the distribution of both groups
```{r}
df_1a <- data.frame(
  values=Y_1a, groups=c(rep("Group 1", n), rep("Group 2", n)))
ggplot(df_1a) +
  geom_density(aes(x=values, fill=groups), alpha=0.4) +
  theme_classic()
```

## 1.B yes treatment effect
```{r}
set.seed(123)
# Generate data
Y_1b <- generate.samples.parallel(
  n_total=n_total, b0=120, sigma_u=20,
  treatment_effect=0.4
  )
# Basic summary
mean_1b <- mean(Y_1b)
mean_1b_group1 <- mean(Y_1b[group_1])
mean_1b_group2 <- mean(Y_1b[group_2])
sd_1b <- sd(Y_1b)
sd_1b_group1 <- sd(Y_1b[group_1])
sd_1b_group2 <- sd(Y_1b[group_2])
cat(mean_1b, mean_1b_group1, mean_1b_group2)
cat(sd_1b, sd_1b_group1, sd_1b_group2)
# Plot
df_1b <- data.frame(
  values=Y_1b, groups=c(rep("Group 1", n), rep("Group 2", n)))
g <- ggplot(df_1b) +
  geom_density(aes(x=values, fill=groups), alpha=0.4) +
  theme_classic()
g
```


# Save datasets
```{r}
write.csv(Y_1a, "../../data/parallel.csv")
write.csv(Y_1b, "../../data/parallel_treatment.csv")
```





